[build]
    command = "npm run build"
    public = ".next"
    function = "netlify/functions"

[build.environment]
    NODE_VERSION = "18"
    NEXT_PRIVATE_TARGET = "server"

[[plugings]]
    package = "@netlify/plugin-nextjs"